### ISSUE TITLE
Request to have option to trigger open of menu programatically

### ISSUE THREAD

**Issue by acarlsen** [composablehorizons/compose-menu#1]
Great library.

I would be nice to be able to open the menu programmatically without using the MenuButton, for example if you also want to show it if using mouse right-click on list item with menu on desktop etc.

**Comment by alexstyl** [comment]
That's definitely something I would like to support and I have something in mind.

if you have a specific api in mind, let me know

**Comment by alexstyl** [comment]
thanks for the input @TomTruyen. valid use case and ill see what i can do

**Comment by Sal7one** [comment]
@TomTruyen Without losing focus is kind of hard on a popup, i'm not sure that's possible? 🤔 
I gave it a couple of trivial tries and failed to do so. maybe you know a way.

but for the request for @acarlsen why not raw dog it?
@alexstyl 

```kotlin
@Stable
public class MenuScope {
    internal var expanded by mutableStateOf(false)
    internal val menuFocusRequester = FocusRequester()
    internal var currentFocusManager by mutableStateOf<FocusManager?>(null)
    internal var hasMenuFocus by mutableStateOf(false)


    public fun expand(isExpanded:Boolean){
            expanded = isExpanded
    }

// pass the scope
public fun Menu(modifier: Modifier = Modifier, scope:MenuScope, contents: @Composable MenuScope.() -> Unit) 

//@Composable
fun App() {
    Column( // used to be box yup, i had a textfield here for testing
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.SpaceBetween,
       modifier=  Modifier.fillMaxSize()
            .background(Brush.linearGradient(listOf(Color(0xFFFED359), Color(0xFFFFBD66))))
            .padding(vertical = 20.dp),
    ) {

        val scope = remember { MenuScope() }

        LaunchedEffect(Unit){
            delay(1500)
            scope.expand(true)
            delay(800)
            scope.expand(false)
            delay(800)
            scope.expand(true)
        }
```

This has worked fairly well, for both of the requests of @TomTruyen and @acarlsen  
Keep in mind that the textfield Looks like this to remove the command after executing it, or it'll keep poping up on click for the textfield again

```kotlin
 SearchBar(
            tfv = text,
            "Some text here",

            onTextChange = {
                text = it
                if(it.text.contains("/open")){
                    // option A delete the command you write - Option A.5 check if unchcanged
                    text = it.copy(text = it.text.replace("/open", ""))

                    // yup same function, same remembered scope
                    scope.expand(true)
                }
            })
```

Sorry for not being much of a help this is the first time I'm seeing KMP code!

**Comment by alexstyl** [comment]
Closing this as done in [1.3.0](https://github.com/composablehorizons/compose-menu/releases/tag/1.3.0)

Here is an example of how to toggle the Menu programmatically:
```kotlin
val state = rememberMenuState(expanded = true)

Menu(state = state) {
    MenuButton {
        BasicText("Toggle the menu")
    }

    MenuContent {
        MenuItem(onClick = { state.expanded = false }) {
            BasicText("Close this menu")
        }
    }
}
```

[More info in the docs](https://composablehorizons.github.io/compose-menu/#expandclose-the-menu-programmatically)

Regarding the typing-to-show-menu request, I have decided to handle it as part of a different issue ([see here](https://github.com/composablehorizons/compose-menu/issues/2)) as it sounds more of a Context Menu than a dropdown menu.
